### ISSUE TITLE
San Nicolas data not available

### ISSUE THREAD

**Issue by eak24** [AguaClara/post.visualize#13]
San Nicolas data is not showing up on the POST visualizations website. This may be due to the name... calling San Nicolas v. Nicolas.

**Comment by jonschristensen** [comment]
I noticed their plant name in recent data in the fusion tables is "Nicolas". I would recommend conforming all instances of Nicolas or San Nicolas to be "San Nicolas" - that's the name that will make the most sense to operators. (They never refer to their town as Nicolas.)

**Comment by eak24** [comment]
@jacuerp has this been pushed to the playstore?

**Comment by eak24** [comment]
@jacuerp what is the status here? Any luck installing Cordova? and Jekyll?

**Comment by jacuerp** [comment]
@ethan92429 I signed the new .apk with the new keystore you generated, but the playstore will not allow me to update the app since the keystores don't correspond. If we can't find the credentials for the original keystore, we may have to issue a new application rather than update the current one.

**Comment by eak24** [comment]
@jacuerp Turns out the old keystore had the same password (in the password/certs drive doc, along with the alias) Crisis averted. I figured out that if you use the intel x_86 system image for your android emulator, it runs way faster than the arm emulator... like 10x. I would use that for testing. You can simply run cordova run android

**Comment by eak24** [comment]
@jacuerp I just uploaded the latest apk with the fixed San Nicolas page and some other minor changes to the playstore. I used the gh-pages branch and I'm about to delete some of the other branches so we don't get confused. Also, I updated the post.visualizations readme to include all the method to this madness
