### ISSUE TITLE
Create a CDC/chlorine Callibration Module

### ISSUE THREAD

**Issue by eak24** [AguaClara/post.visualize#3]
At the plant, the operators check chemical flow rates by timing how long it takes for the coagulant to drain from a fixed volume calibration column. They then perform this calculation:

 `CoagulantDose = CallibrationColumnVolume * CoagulantStockConcentration / CallibrationColumnTimeToEmpty / PlantFlowRate`

However, the only variable that the operators have to measure regularly is the CallibrationColumnTimeToEmpty. If we could help them by presetting the other variables, and measure the time with a built in stopwatch, we may be able to dramatically reduce the time it takes operators to collect dosing information. Same equations/process apply to chlorine dosing.

**Comment by ethan92429** [comment]
Sorry wrong calculCoagulantDose = CallibrationColumnVolume * PlantFlowRate * CoagulantStockConcentration / CallibrationColumnTimeToEmpty

**Comment by eak24** [comment]
We want to launch this functionality straight from the odk collect app. You can learn how to launch an external intent with a regular xml form [here](https://opendatakit.org/help/form-design/external-apps/) and you can have the visualizations app respond to that launched external intent by installing this plugin. Here's a rather [outdated blog post](https://www.raymondcamden.com/2012/05/01/example-of-intents-with-phonegap/) on manually modifying the app to listen for intents and [here's a plugin](https://github.com/napolitano/cordova-plugin-intent) that I believe does the same thing... I think the plugin is the simpler way to go, but the post would give some more information about how it actually works.

**Comment by eak24** [comment]
The operators change the dose setting by moving a slider that looks like [this](https://picasaweb.google.com/100703814570796592714/HondurasTripJanuary2016#slideshow/6256477191331251650) out (away from the entrance tank) to increase coagulant flow rate (toward '100') and in to decrease the flow rate. We want to ask them to record the position of the slider every time that they enter the coagulant. This information should be sent as a separate data point when the form gets sent. Note that this data can be used to create a relationship between slider position and chemical flow rate, and then that relationship can be used to suggest a specific slider location. Another potential use is to monitor how clogged the chemical tubing is, and recommend cleaning based on those numbers.

**Comment by eak24** [comment]
@Shangyuanniu it would be nice to have this finished, or at the very least have it in some sort of passable state before we part ways. Is there any chance you could upload what you have so far to this repo on another branch?

**Comment by eak24** [comment]
@asm278 started a repo to work on this called post.dose
