### ISSUE TITLE
Display by timeCollected rather than timeStarted

### ISSUE THREAD

**Issue by eak24** [AguaClara/post.visualize#8]
Currently. we use timeStarted to display when the operator submitted data. However, we should be using the timeCollected field. Unfortunately the timeCollected field does not include the date information, so it has to be parsed and pieced together using the timeStarted data.

**Comment by jacuerp** [comment]
@ethan92429  Clarifying a few things: 
Right now it seems like you're displaying timeFinished. Are you referring to the guard that chooses which entries to display? In other words, you want to choose which entries to display using timeCollected rather than timeStarted, but you want to continue using timeFinished as the value to display in the table. Is that correct?

**Comment by eak24** [comment]
@jacuerp we should be using timeCollected for everything, because it is the time that the operators claimed they entered the data. Both timeStarted and timeFinished are filled in automatically by the ODK Collect app based on when they started and finished the survey, which may not correspond at all to when they collected the data. The guard code in the visualizations app should be deleted (we should always be displaying all entries that we have in localStorage, which is 100 of the latest sorted by timeStarted as stipulated [here.](https://github.com/AguaClara/post.visualizations/blob/mobile/www/js/db.js#L90)) Then whenever we want to change the data we are pulling, we can programmatically change that SQL query (note how the plantName is programmatically changed to only pull the relevant data.) However, timeCollected doesn't have the actual date built in... which means we have to build the date based on the timeStarted information (I think we can safely assume this is on the same day.) I do this in [this Google script](https://script.google.com/d/1xZryOYajQldAMUSd2dxPnc_6aHnBVIDBaI2zE0ASDUr5EyUZO8a-OkrB/edit?usp=sharing) (which is JS code) when I was trying to parse the backwash time which doesn't include the date. Let me know if you need anything else! And feel free to call/text/gchat anytime and I'll get back ASAP.

**Comment by jacuerp** [comment]
@ethan92429  Would it be poor form to create an extra key in each entry object with this corrected date for easy access downstream? (As opposed to constructing a corrected date for each entry at each stage as the plot is built)

What's gchat?

**Comment by eak24** [comment]
@jacuerp It would definitely be good to just collect and store the correct date in the first place by changing the collection form, which is defined [here](https://github.com/AguaClara/POST/commit/6236d341f2889e6d9dc66d7ab1660f23a1c5ebfa) and uploaded to the Aggregate server. By changing this form, you effect what the keys in the table are. But it has some subtleties I should explain to you. If you'd like to do that, it would make it easier to display the TimeCollected dates. I'm not sure how easy it will be to switch over the form and incorporate all the old data... data migrations can be very tricky. I'll work on starting a an issue to work on the xml defined POST collection form soon, or you could start one! And gchat is google's built in chat through gmail.
